//Deportes
//Añadir deportes
export const AGREGAR_DEPORTE = 'AGREGAR_DEPORTE';
export const AGREGAR_DEPORTE_EXITO = 'AGREGAR_DEPORTE_EXITO';
export const AGREGAR_DEPORTE_ERROR = 'AGREGAR_DEPORTE_ERROR';

// Obtener Deportes
export const COMENZAR_DESCARGA_DEPORTES = 'COMENZAR_DESCARGA_DEPORTES';
export const DESCARGA_DEPORTES_EXITO = 'DESCARGA_DEPORTES_EXITO';
export const DESCARGA_DEPORTE_ERROR = 'DESCARGA_DEPORTE_ERROR';

//Eliminar Deporte
export const OBTENER_DEPORTE_ELIMINAR = "OBTENER_DEPORTE_ELIMINAR";
export const DEPORTE_ELIMINADO_EXITO = "DEPORTE_ELIMINADO_EXITO";
export const DEPORTE_ELIMINADO_ERROR = "DEPORTE_ELIMINADO_ERROR";

//Editar Deporte
export const OBTENER_DEPORTE_EDITAR = 'OBTENER_DEPORTE_EDITAR';
export const COMENZAR_EDICION_DEPORTE = 'COMENZAR_EDICION_DEPORTE';
export const DEPORTE_EDITADO_EXITO = 'DEPORTE_EDITADO_EXITO';
export const DEPORTE_EDITADO_ERROR = 'DEPORTE_EDITADO_ERROR';
//Deportistas
//Añadir deportistas
export const AGREGAR_DEPORTISTA = 'AGREGAR_DEPORTISTA';
export const AGREGAR_DEPORTISTA_EXITO = 'AGREGAR_DEPORTISTA_EXITO';
export const AGREGAR_DEPORTISTA_ERROR = 'AGREGAR_DEPORTISTA_ERROR';

// Obtener deportistas
export const COMENZAR_DESCARGA_DEPORTISTAS = 'COMENZAR_DESCARGA_DEPORTISTAS';
export const DESCARGA_DEPORTISTAS_EXITO = 'DESCARGA_DEPORTISTAS_EXITO';
export const DESCARGA_DEPORTISTA_ERROR = 'DESCARGA_DEPORTISTA_ERROR';

//Eliminar Deporte
export const OBTENER_DEPORTISTA_ELIMINAR = "OBTENER_DEPORTISTA_ELIMINAR";
export const DEPORTISTA_ELIMINADO_EXITO = "DEPORTISTA_ELIMINADO_EXITO";
export const DEPORTISTA_ELIMINADO_ERROR = "DEPORTISTA_ELIMINADO_ERROR";

//Editar DEPORTISTA
export const OBTENER_DEPORTISTA_EDITAR = 'OBTENER_DEPORTISTA_EDITAR';
export const COMENZAR_EDICION_DEPORTISTA = 'COMENZAR_EDICION_DEPORTISTA';
export const DEPORTISTA_EDITADO_EXITO = 'DEPORTISTA_EDITADO_EXITO';
export const DEPORTISTA_EDITADO_ERROR = 'DEPORTISTA_EDITADO_ERROR';

//Churuatas
//Añadir Churuata
export const AGREGAR_CHURUATA = 'AGREGAR_CHURUATA';
export const AGREGAR_CHURUATA_EXITO = 'AGREGAR_CHURUATA_EXITO';
export const AGREGAR_CHURUATA_ERROR = 'AGREGAR_CHURUATA_ERROR';

// Obtener ChCHURUATA
export const COMENZAR_DESCARGA_CHURUATAS = 'COMENZAR_DESCARGA_CHURUATAS';
export const DESCARGA_CHURUATAS_EXITO = 'DESCARGA_CHURUATAS_EXITO';
export const DESCARGA_CHURUATA_ERROR = 'DESCARGA_CHURUATA_ERROR';

//Eliminar cHURUATA
export const OBTENER_CHURUATA_ELIMINAR = "OBTENER_CHURUATA_ELIMINAR";
export const CHURUATA_ELIMINADO_EXITO = "CHURUATA_ELIMINADO_EXITO";
export const CHURUATA_ELIMINADO_ERROR = "CHURUATA_ELIMINADO_ERROR";

//Editar CHURUATA
export const OBTENER_CHURUATA_EDITAR = 'OBTENER_CHURUATA_EDITAR';
export const COMENZAR_EDICION_CHURUATA = 'COMENZAR_EDICION_CHURUATA';
export const CHURUATA_EDITADO_EXITO = 'CHURUATA_EDITADO_EXITO';
export const CHURUATA_EDITADO_ERROR = 'CHURUATA_EDITADO_ERROR';
//Socios
//Añadir SOCIO
export const AGREGAR_SOCIO = 'AGREGAR_SOCIO';
export const AGREGAR_SOCIO_EXITO = 'AGREGAR_SOCIO_EXITO';
export const AGREGAR_SOCIO_ERROR = 'AGREGAR_SOCIO_ERROR';

// Obtener sOCIOS
export const COMENZAR_DESCARGA_SOCIOS = 'COMENZAR_DESCARGA_SOCIOS';
export const DESCARGA_SOCIOS_EXITO = 'DESCARGA_SOCIOS_EXITO';
export const DESCARGA_SOCIO_ERROR = 'DESCARGA_SOCIO_ERROR';

//Eliminar SOCIO
export const OBTENER_SOCIO_ELIMINAR = "OBTENER_SOCIO_ELIMINAR";
export const SOCIO_ELIMINADO_EXITO = "SOCIO_ELIMINADO_EXITO";
export const SOCIO_ELIMINADO_ERROR = "SOCIO_ELIMINADO_ERROR";

//Editar SOCIO
export const OBTENER_SOCIO_EDITAR = 'OBTENER_SOCIO_EDITAR';
export const COMENZAR_EDICION_SOCIO = 'COMENZAR_EDICION_SOCIO';
export const SOCIO_EDITADO_EXITO = 'SOCIO_EDITADO_EXITO';
export const SOCIO_EDITADO_ERROR = 'SOCIO_EDITADO_ERROR';

//Entradas
//Añadir Entrada
export const AGREGAR_ENTRADA = 'AGREGAR_ENTRADA';
export const AGREGAR_ENTRADA_EXITO = 'AGREGAR_ENTRADA_EXITO';
export const AGREGAR_ENTRADA_ERROR = 'AGREGAR_ENTRADA_ERROR';

// Obtener Entradas
export const COMENZAR_DESCARGA_ENTRADAS = 'COMENZAR_DESCARGA_ENTRADAS';
export const DESCARGA_ENTRADAS_EXITO = 'DESCARGA_ENTRADAS_EXITO';
export const DESCARGA_ENTRADA_ERROR = 'DESCARGA_ENTRADA_ERROR';

//Eliminar ENTRADA
export const OBTENER_ENTRADA_ELIMINAR = "OBTENER_ENTRADA_ELIMINAR";
export const ENTRADA_ELIMINADO_EXITO = "ENTRADA_ELIMINADO_EXITO";
export const ENTRADA_ELIMINADO_ERROR = "ENTRADA_ELIMINADO_ERROR";

//Editar ENTRADA
export const OBTENER_ENTRADA_EDITAR = 'OBTENER_ENTRADA_EDITAR';
export const COMENZAR_EDICION_ENTRADA = 'COMENZAR_EDICION_ENTRADA';
export const ENTRADA_EDITADO_EXITO = 'ENTRADA_EDITADO_EXITO';
export const ENTRADA_EDITADO_ERROR = 'ENTRADA_EDITADO_ERROR';

//Locales
//Añadir Locales
export const AGREGAR_LOCAL = 'AGREGAR_LOCAL';
export const AGREGAR_LOCAL_EXITO = 'AGREGAR_LOCAL_EXITO';
export const AGREGAR_LOCAL_ERROR = 'AGREGAR_LOCAL_ERROR';

// Obtener Locales
export const COMENZAR_DESCARGA_LOCALES = 'COMENZAR_DESCARGA_LOCALES';
export const DESCARGA_LOCALES_EXITO = 'DESCARGA_LOCALES_EXITO';
export const DESCARGA_LOCAL_ERROR = 'DESCARGA_LOCAL_ERROR';

//Eliminar LOCAL
export const OBTENER_LOCAL_ELIMINAR = "OBTENER_LOCAL_ELIMINAR";
export const LOCAL_ELIMINADO_EXITO = "LOCAL_ELIMINADO_EXITO";
export const LOCAL_ELIMINADO_ERROR = "LOCAL_ELIMINADO_ERROR";

//Editar LOCAL
export const OBTENER_LOCAL_EDITAR = 'OBTENER_LOCAL_EDITAR';
export const COMENZAR_EDICION_LOCAL = 'COMENZAR_EDICION_LOCAL';
export const LOCAL_EDITADO_EXITO = 'LOCAL_EDITADO_EXITO';
export const LOCAL_EDITADO_ERROR = 'LOCAL_EDITADO_ERROR';

//Alquileres
//Añadir Alquileres
export const AGREGAR_ALQUILER = 'AGREGAR_ALQUILER';
export const AGREGAR_ALQUILER_EXITO = 'AGREGAR_ALQUILER_EXITO';
export const AGREGAR_ALQUILER_ERROR = 'AGREGAR_ALQUILER_ERROR';

// Obtener ALQUILERES
export const COMENZAR_DESCARGA_ALQUILERES = 'COMENZAR_DESCARGA_ALQUILERES';
export const DESCARGA_ALQUILERES_EXITO = 'DESCARGA_ALQUILERES_EXITO';
export const DESCARGA_ALQUILER_ERROR = 'DESCARGA_ALQUILER_ERROR';

//Eliminar Deporte
export const OBTENER_ALQUILER_ELIMINAR = "OBTENER_ALQUILER_ELIMINAR";
export const ALQUILER_ELIMINADO_EXITO = "ALQUILER_ELIMINADO_EXITO";
export const ALQUILER_ELIMINADO_ERROR = "ALQUILER_ELIMINADO_ERROR";

//Editar ALQUILER
export const OBTENER_ALQUILER_EDITAR = 'OBTENER_ALQUILER_EDITAR';
export const COMENZAR_EDICION_ALQUILER = 'COMENZAR_EDICION_ALQUILER';
export const ALQUILER_EDITADO_EXITO = 'ALQUILER_EDITADO_EXITO';
export const ALQUILER_EDITADO_ERROR = 'ALQUILER_EDITADO_ERROR';